### ISSUE TITLE
not working on Lion

### ISSUE THREAD

**Issue by tmm1** [rcarlsen/ShairPortMenu#2]
Got the dreaded "could not open ao device" error.

I was able to `brew install libao` and copy over a new `libao.4.dylib` into the .app to fix it

**Comment by rcarlsen** [comment]
Thanks for this comment...I was revisiting this after a long while...and was having trouble with libao as well. After using homebrew to build and install libao, then linking hairtunes to that version got it all working again. 

This is still a hacky series of scripts, but it does function.

**Comment by rcarlsen** [comment]
Updated to use a system version of libao and instructions for installation with homebrew.
